Repository riscv/riscv-cheri, pull requests merged in 2025-09, with the labels that each got.

#742 Refactor CLRPERM rules
  misc/rv32y_perms.hs
  src/cheri/app-cap-description.adoc
  src/cheri/insns/acperm_32bit.adoc
  src/cheri/riscv-hybrid-integration.adoc
  src/cheri/riscv-unpriv-integration.adoc
  src/cheri/zylevels1.adoc
Labels: change-post-0.9.5

#783 Codify the AUIPC shift being a function of encoding
  src/cheri/app-cap-description.adoc
  src/cheri/insns/auipc_32bit.adoc
Labels: documentation

#780 Add mediated sealing permissions and instructions
  src/cheri/app-cap-description.adoc
  src/cheri/attributes.adoc
  src/cheri/csv/CHERI_ISA.csv
  src/cheri/img/zyseal-acperm_bit_field.edn
  src/cheri/insns/yseal_32bit.adoc
  src/cheri/insns/yunseal_32bit.adoc
  src/cheri/introduction.adoc
  src/cheri/riscv-cheri.adoc
  src/cheri/zyseal.adoc
Labels: Important but after v1.0 ratification, unpriv cheri spec

#808 Clarify exactly which extensions are stable and what we're ratifying for v1.0
  src/cheri/app-cap-description.adoc
  src/cheri/app-cheri-instructions.adoc
  src/cheri/app-standalone-priv-refs.adoc
  src/cheri/app-standalone-unpriv-refs.adoc
  src/cheri/attributes.adoc
  src/cheri/cheri-priv-appendix.adoc
  src/cheri/cheri-unpriv-appendix.adoc
  src/cheri/cheri_csr_tables.adoc
  src/cheri/cheri_isa_tables.adoc
  src/cheri/cheri_priv_isa_tables.adoc
  src/cheri/hypervisor-integration.adoc
  src/cheri/insns/auipc_32bit.adoc
  src/cheri/insns/jalr_32bit.adoc
  src/cheri/introduction.adoc
  src/cheri/ptrmask-integration.adoc
  src/cheri/riscv-cheri.adoc
  src/cheri/riscv-hybrid-integration.adoc
  src/cheri/riscv-unpriv-integration.adoc
  src/cheri/rv32c_mapping_table.adoc
  src/cheri/system.adoc
  src/cheri/vector-integration.adoc
  src/cheri/xycheriot.adoc
  src/cheri/zyseal.adoc
  src/cheri_isa_tables.adoc
  src/hypervisor.adoc
  src/riscv-privileged.adoc
  src/riscv-unprivileged.adoc
  src/v-st-ext.adoc
  src/zc.adoc
  src/zpm.adoc
Labels: documentation
